### ISSUE TITLE
Macro concat error

### ISSUE THREAD

**Issue by dedmen** [SQFvm/vm#58]
```
@SQF#3423 
#define QUOTE(x) #x
#define QGVAR(x) QUOTE(ace_test_##x)
#define HIT_STRUCTURAL QGVAR($#structural)
HIT_STRUCTURAL
```
Actual:
`[WORK]    <STRING>    ace_test_##$#structural`
Expected:
`[WORK]    <STRING>    ace_test_$#structural`

**Comment by dedmen** [comment]
```
@SQF#3423 
#define QUOTE(x) #x
#define MODULE ACE_medical
#define QGVAR(x) QUOTE(MODULE##x)
#define HIT_STRUCTURAL QGVAR($#structural)
[HIT_STRUCTURAL, 0]
```
Actual:
`[WORK]    <ARRAY>    ["ACE_medical#$#structural",0]`
Expected:
`[WORK]    <ARRAY>    ["ACE_medical$#structural",0]`

**Comment by X39** [comment]
Can confirm now, concat is not working in arguments

**Comment by X39** [comment]
The expected result actually is invalid:
Input File
```sqf
#define QUOTE(x) #x
#define QGVAR(x) QUOTE(ace_test_##x)
#define HIT_STRUCTURAL QGVAR($#structural)
HIT_STRUCTURAL
#define QUOTE2(x) #x
#define QGVAR2(x) QUOTE2(#x)
#define HIT_STRUCTURAL2 QGVAR2($#structural)
HIT_STRUCTURAL2
```
Output File
```sqf
#line 1 "C:\Users\marco.silipo\Documents\Arma 3 - Other Profiles\X39\missions\test.VR\pptest2.c"



"ace_test_##$#structural"



"#$#structural"
```

**Comment by X39** [comment]
Still, fixed in 9a198e9d573c98591d52fbfeb2f7f2db48a88552 (according to arma)

**Comment by dedmen** [comment]
>The expected result actually is invalid:
You used different code.

`#define QGVAR(x) QUOTE(ace_test_##x)`

vs
```
#define MODULE ACE_medical
#define QGVAR(x) QUOTE(MODULE##x)
```

```
#define QUOTE2(x) #x
#define QGVAR2(x) QUOTE2(#x)
#define HIT_STRUCTURAL2 QGVAR2($#structural)
HIT_STRUCTURAL2
```
Why are you forcing a `#` to the start using QUOTE2? That's not what my code did.

**Comment by X39** [comment]
Double read, just accidentially copied the second Part too 🙈

**Comment by X39** [comment]
Ahh, now I See, you talk about the second comment you made
Is second still not working as expected I guess?

**Comment by dedmen** [comment]
Both my reproduction code examples where wrong.

`#define QGVAR(x) QUOTE(ace_test_##x)`
`#define QGVAR(x) QUOTE(MODULE##x)` 
Doesn't work as concat inside a argument for another macro is not evaluated before the sub-macro is called.

Here is real reproduction of the whole macro chain without ommiting parts for simplicity and breaking it because I don'tu understand how the preproc works

```
#define QUOTE(x) #x
#define PREFIX ACE
#define COMPONENT medical
#define DOUBLES(var1,var2) ##var1##_##var2
#define ADDON DOUBLES(PREFIX,COMPONENT)

#define GVAR(var1) DOUBLES(ADDON,var1)
#define QGVAR(var1) QUOTE(GVAR(var1))
#define HIT_STRUCTURAL QGVAR($#structural)
entry = HIT_STRUCTURAL
```

That would be example for a config.
