### ISSUE TITLE
[BUG] ASM->SQF conversion array swap

### ISSUE THREAD

**Issue by dedmen** [SQFvm/vm#78]
**Describe the bug**

While writing this test, I had the wrong result flag (true instead of false)
https://github.com/SQFvm/vm/blob/master/tests/sqf/namespace.sqf#L12
And it printed this:
`[CHAT]  SYSTEM: Test !FAILED! '\sqf\namespace.sqf' - 8  { missionNamespace getVariable [false, "don'texist"] }`

The code is
`{ missionNamespace getVariable ["don'texist", false] }`
But the ASM->SQF conversion printed
`{ missionNamespace getVariable [false, "don'texist"] }`
instead. Swapping the array entries.

**To Reproduce**
Change https://github.com/SQFvm/vm/blob/master/tests/sqf/namespace.sqf#L12
to
`["assertEqual", { missionNamespace getVariable ["don'texist", false] }, true],`
and watch the test error

**Comment by X39** [comment]
--> Arrays are reversed

repro: `str {[1,2,3,4,5]}`
