### ISSUE TITLE
allSimpleObjects is scuffed

### ISSUE THREAD

**Issue by eelislynne** [SQFvm/vm#86]
allSimpleObjects is treated as a nular even tho it's a unary.
Right arg is an array: https://community.bistudio.com/wiki/allSimpleObjects

`
lSimpleObjects ["hello"];
               ^
[ERR][L2|C17|__libraryfeed.sqf]    Expected either ';' or ','.
`

**Comment by eelislynne** [comment]
Also same issue with `ctrlTextWidth`
Both can be fixed with `--command-dummy-unary` argument

**Comment by X39** [comment]
Both commands, you list there, are currently not implemented.

SQF-VM is not feature complete and only supports a subset of the available commands (`--command-dummy-*` args are actually there to create the corresponding commands)

If you want a command implemented, please take a look at https://docs.google.com/spreadsheets/d/1kRw1afDwnJvnW67ylmj91CVr8Qs57G7570-5XmnqSD4/edit#gid=0
