### ISSUE TITLE
[BUG] Pasting script with empty lines only executes till empty line

### ISSUE THREAD

**Issue by Grezvany13** [SQFvm/vm#88]
**Describe the bug**
When pasting a piece of code in the VM which contains empty lines, it will only execute the part till the first empty line.

**To Reproduce**
1. Paste the following example in the VM (without empty line):
```sqf
test_fnc_print = {
    params ["_value"];
    diag_log(format ["%1", _value]);
};
["some test"] call text_fnc_print;
```
2. Run the code
3. RESULT: `[WORK]  <ARRAY> ["some test"]`
4. Paste the folling example in the VM (with empty line):
```sqf
test_fnc_print = {
    params ["_value"];
    diag_log(format ["%1", _value]);
};

["some test"] call text_fnc_print;
```
5. Run the code
6. RESULT: `[WORK]  <EMPTY>`
6.a. It also prints the last line (after empty line) as a new piece of code.

**Expected behavior**
I would expect that "any" code, with or without empty lines (for readability) are executed properly.

**Screenshots**
![sqmvm](https://user-images.githubusercontent.com/1245173/66006671-b47cd380-e4af-11e9-80f2-5b04d5250528.jpg)

**Additional context**
Tested with 1.3.1-RC1 (Win64.x64)

**Comment by X39** [comment]
Expected behavior, as mentioned in the first few lines, enter needs to be Pressee twice to run Code.
This means an empty line followed by another enter, will execute the code entered.

If you got a neater idea for this, that will not cause too much hazzle for end users, feel free to suggest
