### ISSUE TITLE
[BUG] Multiple same file includes causes Recursive include detected

### ISSUE THREAD

**Issue by Coryf88** [SQFvm/vm#90]
**Describe the bug**
If a file is included multiple times, `Recursive include detected. Include Tree.` is received.

**To Reproduce**
1. Create empty file named `include.sqf`
2. Execute
```sqf
#include "include.sqf"
#include "include.sqf"
```
3. See error `Recursive include detected. Include Tree.`

**Expected behavior**
No error thrown when including the same file, multiple times.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by X39** [comment]
Thanks for your report, bug is fixed in https://github.com/4d4a5852/vm/commit/226e7e8364533ba8cc4875752004fb40f98fa854
