### ISSUE TITLE
[BUG] Nested IF(N)DEF error with included IF(N)DEF

### ISSUE THREAD

**Issue by Coryf88** [SQFvm/vm#91]
**Describe the bug**
`Unexpected IFNDEF. Already inside of a IFDEF or IFNDEF enclosure.` is received when an `include`, containing a `ifdef`/`ifndef`, is wrapped with a `ifdef`/`ifndef`.

**To Reproduce**
1. Create a file named `include.sqf`, containing:
```sqf
#ifndef UNDEFINED
systemChat "Foo";
#endif
```
2. Execute:
```sqf
#ifndef UNDEFINED
#include "include.sqf"
#endif
```
3. See errror `Unexpected IFNDEF. Already inside of a IFDEF or IFNDEF enclosure.`

**Expected behavior**
No error when if(n)def is used inside of an `include` file, wrapped in a if(n)def.

**Screenshots**
![sqfVM_includeWrapDef](https://user-images.githubusercontent.com/204475/71295652-8090ac00-2342-11ea-841e-a3306bedc78f.png)
![arma_includeWrapDef png](https://user-images.githubusercontent.com/204475/71295656-84243300-2342-11ea-8eb8-b60776114d93.png)

**Additional context**
N/A

**Comment by X39** [comment]
Thanks for your report, Bug is Fixed.
