### ISSUE TITLE
Run SQF Unit Test suites via SQFvm

### ISSUE THREAD

**Issue by xetra11** [SQFvm/vm#93]
**Is your feature request related to a problem? Please describe.**
I would love to run Unit Tests very easily against the SQFvm

**Describe the solution you'd like**
Best case I just refer to my SQF sources and test files and then magic happens

**Describe alternatives you've considered**
no alternatives accepted

**Additional context**
Starting ArmA3 only to see if my unit tests go green is a big time waster. SQFvm could be the best thing existing if a testing engine would be available!

**Comment by X39** [comment]
An example for Unit-Testing can be seen at https://github.com/SQFvm/vm/tree/master/tests

**Comment by xetra11** [comment]
Can't find the line where you can use your own defined functions from other .sqf files

**Comment by X39** [comment]
you need to load SQF code into the VM.
The example shows, how to run a file (the file in this case will then take care of loading the SQF files containing the tests)

it is not planned to include some "load as method" thing as that is not part of arma. Loading methods from places like CfgFunctions requires a script file that converts the methods correspondingly in arma too.
